#!/usr/bin/env bash

<<MIKE
 #Script : Pstermux.sh
 #Date   : 10/19/2021
 #Author : Mike Edwards
 #Version: 0.1
MIKE

termux-open-url https://t.me/CLOWNTERS
sleep 1
termux-open-url https://chat.whatsapp.com/EEpJ3seLYe3Ir7nGI8818m

end="\033[m"
pattern="\033[0;0;0m"
black_n="\033[0;30m"
red_n="\033[0;31m"
green_n="\033[0;32m"
yellow_n="\033[0;33m"
blue_n="\033[0;34m"
pink_n="\033[0;35m"
cyan_n="\033[0;36m"
white_n="\033[0;37m"
black="\033[1;30m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
pink="\033[1;35m"
cyan="\033[1;36m"
white="\033[1;37m"
pblack_n="\[\033[0;30m\]"
pred_n="\[\033[0;31m\]"
pgreen_n="\[\033[0;32m\]"
pyellow_n="\[\033[0;33m\]"
pblue_n="\[\033[0;34m\]"
ppink_n="\[\033[0;35m\]"
pcyan_n="\[\033[0;36m\]"
pwhite="\[\033[0;37m\]"
pwhite="\[\033[1;30m\]"
pred="\[\033[1;31m\]"
pgreen="\[\033[1;32m\]"
pyellow="\[\033[1;33m\]"
pblue="\[\033[1;34m\]"
ppink="\[\033[1;35m\]"
pcyan="\[\033[1;36m\]"
pwhite="\[\033[1;37m\]"
pblack_b="\[\033[40m\]"
pred_b="\[\033[41m\]"
pgreen_b="\[\033[42m\]"
pyellow_b="\[\033[43m\]"
pblue_b="\[\033[44m\]"
ppink_b="\[\033[45m\]"
pcyan_b="\[\033[46m\]"
pwhite_b="\[\033[47m\]"

[[ -f .okay ]] || pkg i -y figlet &> /dev/null
> .okay

for((a=0;a<=2;a++)); do
    clear
    read -p " What's your name: " name
    [[ -n ${name} ]] && break || echo " empty. not?"
    sleep 1
done

ps1="\"${pred}┌─(${pgreen}${name}${pred})${pyellow}@${pred}(${pgreen}Termux${pred})${pwhite}:${pblue_n}\w\n${pred}└─\#─≽${pgreen} \$ ${pgreen_n}\""
printf "clear
name=\"${name}\"
figlet ${name}
PS1=${ps1}" > ~/.bashrc
